[package]
name = "running"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba = { version = "0.5.2" }
gbamath = { path = "../lib/gbamath" }
gbainputs = { path = "../lib/gbainputs" }